albumy/forms/main.py
# -*- coding: utf-8 -*-
"""
    :author: Grey Li (李辉)
    :url: http://greyli.com
    :copyright: © 2018 Grey Li <withlihui@gmail.com>
    :license: MIT, see LICENSE for more details.
"""
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Optional, Length


class DescriptionForm(FlaskForm):
    description = TextAreaField('Description', validators=[Optional(), Length(0, 500)])
    submit = SubmitField()


class TagForm(FlaskForm):
    tag = StringField('Add Tag (use space to separate)', validators=[Optional(), Length(0, 64)])
    submit = SubmitField()


class CommentForm(FlaskForm):
    body = TextAreaField('', validators=[DataRequired()])
    submit = SubmitField()

albumy/blueprints/ajax.py
# -*- coding: utf-8 -*-
"""
    :author: Grey Li (李辉)
    :url: http://greyli.com
    :copyright: © 2018 Grey Li <withlihui@gmail.com>
    :license: MIT, see LICENSE for more details.
"""
from flask import render_template, jsonify, Blueprint
from flask_login import current_user

from albumy.models import User, Photo, Notification
from albumy.notifications import push_collect_notification, push_follow_notification

ajax_bp = Blueprint('ajax', __name__)


@ajax_bp.route('/notifications-count')
def notifications_count():
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    count = Notification.query.with_parent(current_user).filter_by(is_read=False).count()
    return jsonify(count=count)


@ajax_bp.route('/profile/<int:user_id>')
def get_profile(user_id):
    user = User.query.get_or_404(user_id)
    return render_template('main/profile_popup.html', user=user)


@ajax_bp.route('/followers-count/<int:user_id>')
def followers_count(user_id):
    user = User.query.get_or_404(user_id)
    count = user.followers.count() - 1  # minus user self
    return jsonify(count=count)


@ajax_bp.route('/<int:photo_id>/followers-count')
def collectors_count(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    count = len(photo.collectors)
    return jsonify(count=count)


@ajax_bp.route('/collect/<int:photo_id>', methods=['POST'])
def collect(photo_id):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403
    if not current_user.confirmed:
        return jsonify(message='Confirm account required.'), 400
    if not current_user.can('COLLECT'):
        return jsonify(message='No permission.'), 403

    photo = Photo.query.get_or_404(photo_id)
    if current_user.is_collecting(photo):
        return jsonify(message='Already collected.'), 400

    current_user.collect(photo)
    if current_user != photo.author and photo.author.receive_collect_notification:
        push_collect_notification(collector=current_user, photo_id=photo_id, receiver=photo.author)
    return jsonify(message='Photo collected.')


@ajax_bp.route('/uncollect/<int:photo_id>', methods=['POST'])
def uncollect(photo_id):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    photo = Photo.query.get_or_404(photo_id)
    if not current_user.is_collecting(photo):
        return jsonify(message='Not collect yet.'), 400

    current_user.uncollect(photo)
    return jsonify(message='Collect canceled.')


@ajax_bp.route('/follow/<username>', methods=['POST'])
def follow(username):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403
    if not current_user.confirmed:
        return jsonify(message='Confirm account required.'), 400
    if not current_user.can('FOLLOW'):
        return jsonify(message='No permission.'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if current_user.is_following(user):
        return jsonify(message='Already followed.'), 400

    current_user.follow(user)
    if user.receive_collect_notification:
        push_follow_notification(follower=current_user, receiver=user)
    return jsonify(message='User followed.')


@ajax_bp.route('/unfollow/<username>', methods=['POST'])
def unfollow(username):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if not current_user.is_following(user):
        return jsonify(message='Not follow yet.'), 400

    current_user.unfollow(user)
    return jsonify(message='Follow canceled.')

albumy/blueprints/main.py
# -*- coding: utf-8 -*-
"""
    :author: Grey Li (李辉)
    :url: http://greyli.com
    :copyright: © 2018 Grey Li <withlihui@gmail.com>
    :license: MIT, see LICENSE for more details.
"""
import os

from flask import render_template, flash, redirect, url_for, current_app, \
    send_from_directory, request, abort, Blueprint
from flask_login import login_required, current_user
from sqlalchemy.sql.expression import func

from albumy.decorators import confirm_required, permission_required
from albumy.extensions import db
from albumy.forms.main import DescriptionForm, TagForm, CommentForm
from albumy.models import User, Photo, Tag, Follow, Collect, Comment, Notification
from albumy.notifications import push_comment_notification, push_collect_notification
from albumy.utils import rename_image, resize_image, redirect_back, flash_errors

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        per_page = current_app.config['ALBUMY_PHOTO_PER_PAGE']
        pagination = Photo.query \
            .join(Follow, Follow.followed_id == Photo.author_id) \
            .filter(Follow.follower_id == current_user.id) \
            .order_by(Photo.timestamp.desc()) \
            .paginate(page, per_page)
        photos = pagination.items
    else:
        pagination = None
        photos = None
    tags = Tag.query.join(Tag.photos).group_by(Tag.id).order_by(func.count(Photo.id).desc()).limit(10)
    return render_template('main/index.html', pagination=pagination, photos=photos, tags=tags, Collect=Collect)


@main_bp.route('/explore')
def explore():
    photos = Photo.query.order_by(func.random()).limit(12)
    return render_template('main/explore.html', photos=photos)


@main_bp.route('/search')
def search():
    q = request.args.get('q', '').strip()
    if q == '':
        flash('Enter keyword about photo, user or tag.', 'warning')
        return redirect_back()

    category = request.args.get('category', 'photo')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ALBUMY_SEARCH_RESULT_PER_PAGE']
    if category == 'user':
        pagination = User.query.whooshee_search(q).paginate(page, per_page)
    elif category == 'tag':
        pagination = Tag.query.whooshee_search(q).paginate(page, per_page)
    else:
        pagination = Photo.query.whooshee_search(q).paginate(page, per_page)
    results = pagination.items
    return render_template('main/search.html', q=q, results=results, pagination=pagination, category=category)


@main_bp.route('/notifications')
@login_required
def show_notifications():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ALBUMY_NOTIFICATION_PER_PAGE']
    notifications = Notification.query.with_parent(current_user)
    filter_rule = request.args.get('filter')
    if filter_rule == 'unread':
        notifications = notifications.filter_by(is_read=False)

    pagination = notifications.order_by(Notification.timestamp.desc()).paginate(page, per_page)
    notifications = pagination.items
    return render_template('main/notifications.html', pagination=pagination, notifications=notifications)


@main_bp.route('/notification/read/<int:notification_id>', methods=['POST'])
@login_required
def read_notification(notification_id):
    notification = Notification.query.get_or_404(notification_id)
    if current_user != notification.receiver:
        abort(403)

    notification.is_read = True
    db.session.commit()
    flash('Notification archived.', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/notifications/read/all', methods=['POST'])
@login_required
def read_all_notification():
    for notification in current_user.notifications:
        notification.is_read = True
    db.session.commit()
    flash('All notifications archived.', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/uploads/<path:filename>')
def get_image(filename):
    return send_from_directory(current_app.config['ALBUMY_UPLOAD_PATH'], filename)


@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/upload', methods=['GET', 'POST'])
@login_required
@confirm_required
@permission_required('UPLOAD')
def upload():
    if request.method == 'POST' and 'file' in request.files:
        f = request.files.get('file')
        filename = rename_image(f.filename)
        f.save(os.path.join(current_app.config['ALBUMY_UPLOAD_PATH'], filename))
        filename_s = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['small'])
        filename_m = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['medium'])
        photo = Photo(
            filename=filename,
            filename_s=filename_s,
            filename_m=filename_m,
            author=current_user._get_current_object()
        )
        db.session.add(photo)
        db.session.commit()
    return render_template('main/upload.html')


@main_bp.route('/photo/<int:photo_id>')
def show_photo(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ALBUMY_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(photo).order_by(Comment.timestamp.asc()).paginate(page, per_page)
    comments = pagination.items

    comment_form = CommentForm()
    description_form = DescriptionForm()
    tag_form = TagForm()

    description_form.description.data = photo.description
    return render_template('main/photo.html', photo=photo, comment_form=comment_form,
                           description_form=description_form, tag_form=tag_form,
                           pagination=pagination, comments=comments)


@main_bp.route('/photo/n/<int:photo_id>')
def photo_next(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    photo_n = Photo.query.with_parent(photo.author).filter(Photo.id < photo_id).order_by(Photo.id.desc()).first()

    if photo_n is None:
        flash('This is already the last one.', 'info')
        return redirect(url_for('.show_photo', photo_id=photo_id))
    return redirect(url_for('.show_photo', photo_id=photo_n.id))


@main_bp.route('/photo/p/<int:photo_id>')
def photo_previous(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    photo_p = Photo.query.with_parent(photo.author).filter(Photo.id > photo_id).order_by(Photo.id.asc()).first()

    if photo_p is None:
        flash('This is already the first one.', 'info')
        return redirect(url_for('.show_photo', photo_id=photo_id))
    return redirect(url_for('.show_photo', photo_id=photo_p.id))


@main_bp.route('/collect/<int:photo_id>', methods=['POST'])
@login_required
@confirm_required
@permission_required('COLLECT')
def collect(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    if current_user.is_collecting(photo):
        flash('Already collected.', 'info')
        return redirect(url_for('.show_photo', photo_id=photo_id))

    current_user.collect(photo)
    flash('Photo collected.', 'success')
    if current_user != photo.author and photo.author.receive_collect_notification:
        push_collect_notification(collector=current_user, photo_id=photo_id, receiver=photo.author)
    return redirect(url_for('.show_photo', photo_id=photo_id))


@main_bp.route('/uncollect/<int:photo_id>', methods=['POST'])
@login_required
def uncollect(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    if not current_user.is_collecting(photo):
        flash('Not collect yet.', 'info')
        return redirect(url_for('.show_photo', photo_id=photo_id))

    current_user.uncollect(photo)
    flash('Photo uncollected.', 'info')
    return redirect(url_for('.show_photo', photo_id=photo_id))


@main_bp.route('/report/comment/<int:comment_id>', methods=['POST'])
@login_required
@confirm_required
def report_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.flag += 1
    db.session.commit()
    flash('Comment reported.', 'success')
    return redirect(url_for('.show_photo', photo_id=comment.photo_id))


@main_bp.route('/report/photo/<int:photo_id>', methods=['POST'])
@login_required
@confirm_required
def report_photo(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    photo.flag += 1
    db.session.commit()
    flash('Photo reported.', 'success')
    return redirect(url_for('.show_photo', photo_id=photo.id))


@main_bp.route('/photo/<int:photo_id>/collectors')
def show_collectors(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ALBUMY_USER_PER_PAGE']
    pagination = Collect.query.with_parent(photo).order_by(Collect.timestamp.asc()).paginate(page, per_page)
    collects = pagination.items
    return render_template('main/collectors.html', collects=collects, photo=photo, pagination=pagination)


@main_bp.route('/photo/<int:photo_id>/description', methods=['POST'])
@login_required
def edit_description(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    if current_user != photo.author and not current_user.can('MODERATE'):
        abort(403)

    form = DescriptionForm()
    if form.validate_on_submit():
        photo.description = form.description.data
        db.session.commit()
        flash('Description updated.', 'success')

    flash_errors(form)
    return redirect(url_for('.show_photo', photo_id=photo_id))


@main_bp.route('/photo/<int:photo_id>/comment/new', methods=['POST'])
@login_required
@permission_required('COMMENT')
def new_comment(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    page = request.args.get('page', 1, type=int)
    form = CommentForm()
    if form.validate_on_submit():
        body = form.body.data
        author = current_user._get_current_object()

albumy/templates/main/_photo_sidebar.html
{% from 'macros.html' import follow_area with context %}

<nav aria-label="Page navigation">
    <ul class="pagination">
        <li class="page-item">
            <a class="page-link" href="{{ url_for('.photo_previous', photo_id=photo.id) }}">&larr;Previous</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="{{ url_for('.photo_next', photo_id=photo.id) }}">Next&rarr;</a>
        </li>
    </ul>
</nav>
<div class="card bg-light mb-3 w-100 sidebar-card">
    <div class="card-body">
        <div class="row">
            <a href="{{ url_for('user.index', username=photo.author.username) }}">
                <img class="sidebar-avatar rounded avatar-m"
                     src="{{ url_for('main.get_avatar', filename=photo.author.avatar_m) }}">
            </a>
            <div class="sidebar-profile">
                <h6 class="card-title">
                    <a href="{{ url_for('user.index', username=photo.author.username) }}">{{ photo.author.name }}</a>
                </h6>
                <p class="card-subtitle mb-2 text-muted">{{ photo.author.username }}</p>
                {{ follow_area(photo.author) }}
            </div>
        </div>
    </div>
</div>
<div class="card bg-light mb-3 w-100">
    <div class="card-body">
        <div id="description">
            <p>
                {% if photo.description %}
                    {{ photo.description }}
                {% endif %}
                {% if current_user == photo.author %}
                    <a id="description-btn" href="#!">
                        <small><span class="oi oi-pencil"></span> edit description</small>
                    </a>
                {% endif %}
            </p>
        </div>
        {% if current_user == photo.author %}
            <div id="description-form">
                <form action="{{ url_for('.edit_description', photo_id=photo.id) }}" method="post">
                    {{ description_form.csrf_token }}
                    {{ render_field(description_form.description) }}
                    <a class="btn btn-light btn-sm" id="cancel-description">Cancel</a>
                    {{ render_field(description_form.submit, class='btn btn-success btn-sm') }}
                </form>
            </div>
        {% endif %}
        <div id="tags">
            <p>
                {% if photo.tags %}
                    {% for tag in photo.tags %}
                        <a class="badge badge-light"
                           href="{{ url_for('.show_tag', tag_id=tag.id) }}" target="_blank"><span
                                class="oi oi-tag"></span> {{ tag.name }}</a>
                    {% endfor %}
                {% endif %}
                {% if current_user == photo.author %}
                    <a id="tag-btn" href="#!">
                        <small><span class="oi oi-pencil"></span> edit tag</small>
                    </a>
                {% endif %}
            </p>
        </div>
        {% if current_user == photo.author %}
            <div id="tag-form">
                <form action="{{ url_for('.new_tag', photo_id=photo.id) }}" method="post">
                    {{ tag_form.csrf_token }}
                    {{ render_field(tag_form.tag) }}
                    <a class="btn btn-light btn-sm" id="cancel-tag">Cancel</a>
                    {{ render_field(tag_form.submit, class='btn btn-success btn-sm') }}
                </form>
                {% if photo.tags %}
                    <hr>
                    {% for tag in photo.tags %}
                        <a class="dead-link" href="#!"
                           data-href="{{ url_for('.delete_tag', photo_id=photo.id, tag_id=tag.id) }}"
                           data-toggle="modal" data-target="#confirm-delete" title="Delete tag">
                <span class="badge badge-danger">
                {{ tag.name }} <span class="oi oi-trash" aria-hidden="true"></span>
            </span>
                        </a>
                    {% endfor %}
                {% endif %}
            </div>
        {% endif %}
        {% if current_user.is_authenticated %}
            {% if current_user.is_collecting(photo) %}
                <form class="inline" method="post"
                      action="{{ url_for('main.uncollect', photo_id=photo.id) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-outline-secondary btn-sm">
                        <span class="oi oi-x"></span> Uncollect
                    </button>
                </form>
            {% else %}
                <form class="inline" method="post"
                      action="{{ url_for('main.collect', photo_id=photo.id) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-outline-primary btn-sm">
                        <span class="oi oi-star"></span> Collect
                    </button>
                </form>
            {% endif %}
        {% else %}
            <form class="inline" method="post" action="{{ url_for('main.collect', photo_id=photo.id) }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <button type="submit" class="btn btn-primary btn-sm">
                    <span class="oi oi-star"></span> Collect
                </button>
            </form>
        {% endif %}
        {% if photo.collectors %}
            <a href="{{ url_for('main.show_collectors', photo_id=photo.id) }}">{{ photo.collectors|length }}
                collectors</a>
        {% endif %}
    </div>
</div>

albumy/templates/main/_sidebar.html
<div class="card bg-light mb-3 w-100 sidebar-nav">
    <div class="card-body">
        <div class="row">
            <a href="{{ url_for('user.index', username=current_user.username) }}">
                <img class="rounded avatar-s" style="margin-left: 15px; position: absolute"
                     src="{{ url_for('main.get_avatar', filename=current_user.avatar_m) }}">
            </a>
            <div class="sidebar-nav-name">
                <h6 class="card-title"><a
                        href="{{ url_for('user.index', username=current_user.username) }}">{{ current_user.name }}
                </a></h6>
                <p class="card-subtitle mb-2 text-muted">{{ current_user.username }}</p>
            </div>
        </div>
        <a class="card-link" href="{{ url_for('user.index', username=current_user.username) }}">
            <span class="oi oi-home"></span> My Photos
        </a><br>
        <a class="card-link" href="{{ url_for('user.show_collections', username=current_user.username) }}">
            <span class="oi oi-star"></span> My Collections
        </a>
    </div>
</div>
<div class="card bg-light mb-3 w-100">
    <div class="card-header">Hot Tags</div>
    <div class="list-group">
        {% for tag in tags %}
            <a class="list-group-item" href="{{ url_for('.show_tag', tag_id=tag.id) }}">{{ tag.name }}
                <span class="badge badge-pill">{{ tag.photos|length }}</span>
            </a>
        {% endfor %}
    </div>
</div>

albumy/templates/main/collectors.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}

{% block title %}Collectors{% endblock %}

{% block content %}
    <div class="page-header">
        <div class="row">
            <div class="col-md-12">
                <a class="btn btn-default btn-sm" href="{{ url_for('main.show_photo', photo_id=photo.id) }}">
                    <span class="oi oi-arrow-left" aria-hidden="true"></span> Return
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3>{{ photo.collectors|length }} Collectors</h3>
            {% for collect in collects %}
                {{ user_card(user=collect.collector) }}
            {% endfor %}
        </div>
    </div>
    {% if collects %}
        <div class="page-footer">
            {{ render_pagination(pagination, align='center') }}
        </div>
    {% endif %}
{% endblock %}

albumy/templates/main/explore.html
{% extends 'base.html' %}
{% from 'macros.html' import photo_card with context %}

{% block title %}Explore{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% for photo in photos %}
                {{ photo_card(photo) }}
            {% endfor %}
        </div>
    </div>
    <div class="text-center">
        <a class="btn btn-primary" href="{{ url_for('.explore') }}">
            <span class="oi oi-loop-circular"></span> Change
        </a>
    </div>
{% endblock %}

albumy/templates/main/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import photo_card with context %}

{% block title %}Home{% endblock %}

{% block content %}
{% if current_user.is_authenticated %}
    <div class="row justify-content-md-center">
        <div class="col-md-8">
            {% if photos %}
                {% for photo in photos %}
                    <div class="card mb-3 w-100 bg-light">
                        <div class="card-header">
                            <a class="dead-link" href="{{ url_for('user.index', username=photo.author.username) }}">
                                <img class="rounded img-fluid avatar-s profile-popover"
                                     data-href="{{ url_for('ajax.get_profile', user_id=photo.author.id) }}"
                                     src="{{ url_for('main.get_avatar', filename=photo.author.avatar_m) }}">
                            </a>
                            <a class="profile-popover trend-card-avatar"
                               data-href="{{ url_for('ajax.get_profile', user_id=photo.author.id) }}"
                               href="{{ url_for('user.index', username=photo.author.username) }}">{{ photo.author.name }}</a>
                            <span class="float-right">
                <small data-toggle="tooltip" data-placement="top" data-timestamp="{{ photo.timestamp }}"
                       data-delay="500">
                    {{ moment(photo.timestamp).fromNow(refresh=True) }}</small></span>
                        </div>
                        <div class="card-body">
                            <div class="" align="center">
                                <a class="thumbnail" href="{{ url_for('.show_photo', photo_id=photo.id) }}"
                                   target="_blank">
                                    <img class="img-fluid"
                                         src="{{ url_for('.get_image', filename=photo.filename_m) }}">
                                </a>
                            </div>
                        </div>
                        <div class="card-footer">
                            <span class="oi oi-star"></span>
                            <span id="collectors-count-{{ photo.id }}"
                                  data-href="{{ url_for('ajax.collectors_count', photo_id=photo.id) }}">
                                {{ photo.collectors|length }}
                            </span>
                            <span class="oi oi-comment-square"></span> {{ photo.comments|length }}
                            <div class="float-right">
                                {% if current_user.is_authenticated %}
                                    <button class="{% if not current_user.is_collecting(photo) %}hide{% endif %}
                                     btn btn-outline-secondary btn-sm uncollect-btn"
                                            data-href="{{ url_for('ajax.uncollect', photo_id=photo.id) }}"
                                            data-id="{{ photo.id }}">
                                        <span class="oi oi-x"></span> Uncollect
                                    </button>
                                    <button class="{% if current_user.is_collecting(photo) %}hide{% endif %}
                                     btn btn-outline-primary btn-sm collect-btn"
                                            data-href="{{ url_for('ajax.collect', photo_id=photo.id) }}"
                                            data-id="{{ photo.id }}">
                                        <span class="oi oi-star"></span> Collect
                                    </button>
                                {% else %}
                                    <form class="inline" method="post"
                                          action="{{ url_for('main.collect', photo_id=photo.id) }}">
                                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-outline-primary btn-sm">
                                            <span class="oi oi-star"></span> Collect
                                        </button>
                                    </form>
                                {% endif %}
                            </div>
                            {% if photo.description %}
                                <p class="card-text">{{ photo.description }}</p>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="tip text-center">
                    <h3>No trends.</h3>
                    <p><a href="{{ url_for('.explore') }}">Explore</a></p>
                </div>
            {% endif %}
        </div>
        <div class="col-md-3">
            {% include 'main/_sidebar.html' %}
        </div>
    </div>
    {% if photos %}
        {{ render_pagination(pagination, align='center') }}
    {% endif %}
{% else %}
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-8">
                <img src="{{ url_for('static', filename='images/index.jpg') }}" class="rounded img-fluid">
            </div>
            <div class="col-md-4 align-self-center">
                <h1>Albumy</h1>
                <p>Capture and remember every wonderful moment.</p>
                <p><a class="btn btn-primary btn-lg" href="{{ url_for('auth.register') }}">Join Now</a></p>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

albumy/templates/main/profile_popup.html
<div class="popup-card">
    <img class="rounded img-fluid avatar-s popup-avatar" src="{{ url_for('main.get_avatar', filename=user.avatar_m) }}">
    <div class="popup-profile">
        <h6>{{ user.name }}</h6>
        <p class="text-muted">{{ user.username }}
            {% if current_user.is_authenticated %}
                {% if current_user != user and current_user.is_followed_by(user) %}
                    {% if user.is_followed_by(current_user) %}
                        <span class="badge badge-light">Follow each other</span>
                    {% else %}
                        <span class="badge badge-light">Follows you</span>
                    {% endif %}
                {% endif %}
            {% endif %}
        </p>
    </div>
    <p class="card-text">
        <a href="{{ url_for('user.index', username=user.username) }}">
            <strong>{{ user.photos|length }}</strong> Photos
        </a>&nbsp;
        <a href="{{ url_for('user.show_followers', username=user.username) }}">
            <strong id="followers-count-{{ user.id }}"
                    data-href="{{ url_for('ajax.followers_count', user_id=user.id) }}">
                {{ user.followers.count() - 1 }}
            </strong> Followers
        </a>
    </p>
    <a href="{{ url_for('user.index', username=user.username) }}" class="btn btn-light btn-sm">Homepage</a>
    {% if current_user.is_authenticated %}
        {% if user != current_user %}
            <button data-id="{{ user.id }}"
                    data-href="{{ url_for('ajax.unfollow', username=user.username) }}"
                    class="{% if not current_user.is_following(user) %}hide{% endif %} btn btn-dark btn-sm unfollow-btn">
                Unfollow
            </button>
            <button data-id="{{ user.id }}"
                    data-href="{{ url_for('ajax.follow', username=user.username) }}"
                    class="{% if current_user.is_following(user) %}hide{% endif %} btn btn-primary btn-sm follow-btn">
                Follow
            </button>
        {% endif %}
    {% else %}
        <form class="inline" method="post"
              action="{{ url_for('user.follow', username=user.username) }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <button type="submit" class="btn btn-primary btn-sm">Follow</button>
        </form>
    {% endif %}
</div>